name: Pull Request Validation

on: pull_request

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, ' ' ) }}

jobs:
  check-type-label:
    name: Check changelog
    runs-on: ubuntu-latest
    steps:
      - if: contains( env.LABELS, 'changelog:' ) == false
        run: exit 1
  check-milestone:
    name: Check milestone
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.milestone == null
        run: exit 1
